### ISSUE TITLE
defaultのsub namespaceに所属するメソッドは、他のsub namespaceからもcallできるようにする

### ISSUE THREAD

**Issue by otolab** [plaidev/minimum-rpc#7]
refs https://github.com/plaidev/karte-io/issues/8558

sub_name_space毎に全てのメソッドを登録し直す必要があるので、デフォルトのsub_name_spaceに存在するメソッドは、prototype的に他のsub namespaceから参照できるようにする。

**Comment by nashibao** [comment]
@otolab というより、、methods登録時にsub_name_spaceは必要なくないです？わかりづらくなる気がする。

**Comment by otolab** [comment]
> @otolab というより、、methods登録時にsub_name_spaceは必要なくないです？わかりづらくなる気がする。

アクセス制限のためにsub_name_spaceを。という話がありましたが、それだと`@connection`で制御するのと変わらないような気がします。どのsub_name_spaceで接続しても同じメソッドしか呼べないのであれば、結局minimum-rpcのレベルでは「接続を受け付けるかどうか」の違いしかなくなってしまうと思います。

だとすると、minimum-rpcではsub_name_spaceを廃止して、bolt-rpc側に移すのではどうですか？

ちなみに[1.0.0の時点](https://github.com/plaidev/minimum-rpc/blob/529bdc226d59f4b11a5887880462a5a02c658ae1/src/server.coffee)では、bolt-rpcがsub_name_spaceを使っていませんでした。もし使っていたとすると、
- sub_name_space毎(＝minimum-rpcサーバ毎)にメソッドが分かれる
- sub_name_spaceのアクセス制限のチェックは効いていない

状態でした。
