### ISSUE TITLE
sub-namespaceを廃止。join周りのコードとして整理

### ISSUE THREAD

**Issue by otolab** [plaidev/minimum-rpc#8]
refs #7

**Comment by nashibao** [comment]
@otolab minimum-rpc側に authorization という意味合いは必要ないんですが、そこは大丈夫ですかね？ (authとしてkarte-io側で利用する、という意味合い）

**Comment by otolab** [comment]
@nashibao うーん、そうなんですね..。

sub_name_spaceの意味を勘違いしていたようです。
もともとのコードを見返してみたのですが、
一つのname_spaceに対して、内容の異なる複数のサーバを立てられる機能。ということであっていますか？

```
app = require("http").createServer()
io = require("socket.io")(app
server = new Server(io, undefined, {name_space: 'project'})
server2 = new Server(io, undefined, {name_space: 'project', sub_name_space: 'test'})

server.set 'add', (a, b, cb) -> cb a+b
server2.set 'add', (a, b, cb) -> cb a+b+1

# client
client = new Client io_for_client, {url: 'http://localhost:2000', name_space: 'project'}
client2 = new Client io_for_client, {url: 'http://localhost:2000', name_space: 'project', sub_name_space: 'test'}
```

だとすると、現在のKARTEでは「api_keyだけ異なる複数のサーバを立てたくない」という命題があるので、単に使わない方向が良いように思います。

また、socket.ioの中ではパスは仮想的なものらしいので、`name_space: 'project' + '/' + 'test'`でもあまり変わらないのではないかなと思いました。
この部分はどういう意図ですか？
